// <auto-generated />
using System;
using EnglishCenter.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishCenter.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260312104506_SeedAdminUser")]
    partial class SeedAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurriculumTeacher", b =>
                {
                    b.Property<int>("ParticipantTeachersTeacherId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipatedCurriculumsCurriculumId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantTeachersTeacherId", "ParticipatedCurriculumsCurriculumId");

                    b.HasIndex("ParticipatedCurriculumsCurriculumId");

                    b.ToTable("CurriculumTeacher", (string)null);
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("ClassId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ClassName = "test",
                            CourseId = 1,
                            EndDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 20,
                            Room = "Room 101",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            TeacherId = 1
                        },
                        new
                        {
                            ClassId = 2,
                            ClassName = "ENG101-A2",
                            CourseId = 1,
                            EndDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudents = 15,
                            Room = "Room 102",
                            StartDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            TeacherId = 2
                        });
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationInWeeks")
                        .HasColumnType("int");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseCode = "ENG101",
                            CourseName = "English for Beginners",
                            Description = "Basic English course for absolute beginners",
                            DurationInWeeks = 12,
                            Fee = 2000000m,
                            IsActive = true,
                            Level = "Beginner",
                            TotalHours = 48
                        },
                        new
                        {
                            CourseId = 2,
                            CourseCode = "ENG102",
                            CourseName = "Elementary English",
                            Description = "English course for elementary level students",
                            DurationInWeeks = 12,
                            Fee = 2500000m,
                            IsActive = true,
                            Level = "Elementary",
                            TotalHours = 48
                        },
                        new
                        {
                            CourseId = 3,
                            CourseCode = "ENG201",
                            CourseName = "Intermediate English",
                            Description = "English course for intermediate level students",
                            DurationInWeeks = 16,
                            Fee = 3000000m,
                            IsActive = true,
                            Level = "Intermediate",
                            TotalHours = 64
                        },
                        new
                        {
                            CourseId = 4,
                            CourseCode = "ENG301",
                            CourseName = "Advanced English",
                            Description = "Advanced English course for fluent speakers",
                            DurationInWeeks = 16,
                            Fee = 3500000m,
                            IsActive = true,
                            Level = "Advanced",
                            TotalHours = 64
                        },
                        new
                        {
                            CourseId = 5,
                            CourseCode = "IELTS01",
                            CourseName = "IELTS Preparation",
                            Description = "Intensive IELTS exam preparation course",
                            DurationInWeeks = 20,
                            Fee = 5000000m,
                            IsActive = true,
                            Level = "Intermediate",
                            TotalHours = 80
                        });
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Curriculum", b =>
                {
                    b.Property<int>("CurriculumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurriculumId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurriculumName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CurriculumId");

                    b.HasIndex("ClassId");

                    b.ToTable("Curriculums");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.CurriculumDay", b =>
                {
                    b.Property<int>("CurriculumDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurriculumDayId"));

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionCount")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CurriculumDayId");

                    b.HasIndex("CurriculumId");

                    b.ToTable("CurriculumDays");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.CurriculumSession", b =>
                {
                    b.Property<int>("CurriculumSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurriculumSessionId"));

                    b.Property<int>("CurriculumDayId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SessionDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("CurriculumSessionId");

                    b.HasIndex("CurriculumDayId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("CurriculumSessions");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            ClassId = 1,
                            EnrollmentDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            ClassId = 1,
                            EnrollmentDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 3,
                            ClassId = 1,
                            EnrollmentDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("CurriculumSessionId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("LessonNumber")
                        .HasColumnType("int");

                    b.Property<string>("LessonTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Resources")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("LessonId");

                    b.HasIndex("CurriculumSessionId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 2000000m,
                            Notes = "Full payment for English for Beginners course",
                            PaymentDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Bank Transfer",
                            Status = "Completed",
                            StudentId = 1
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 2000000m,
                            Notes = "Full payment for English for Beginners course",
                            PaymentDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            Status = "Completed",
                            StudentId = 2
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 2000000m,
                            Notes = "Full payment for English for Beginners course",
                            PaymentDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Credit Card",
                            Status = "Completed",
                            StudentId = 3
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 500000m,
                            Notes = "Partial payment for additional materials",
                            PaymentDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Bank Transfer",
                            Status = "Completed",
                            StudentId = 1
                        },
                        new
                        {
                            PaymentId = 5,
                            Amount = 300000m,
                            Notes = "Late fee payment",
                            PaymentDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            Status = "Completed",
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("EnglishCenter.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<TimeSpan>("AvailableEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("AvailableStartTime")
                        .HasColumnType("time");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Address = "123 Nguyễn Huệ, Q1, TP.HCM",
                            Avatar = "",
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "a.nguyen@email.com",
                            EnrollmentDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Văn A",
                            IsActive = true,
                            Level = "Beginner",
                            Password = "",
                            PhoneNumber = "0901234567",
                            Username = ""
                        },
                        new
                        {
                            StudentId = 2,
                            Address = "456 Lê Lợi, Q3, TP.HCM",
                            Avatar = "",
                            DateOfBirth = new DateTime(1998, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "b.tran@email.com",
                            EnrollmentDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trần Thị B",
                            IsActive = true,
                            Level = "Elementary",
                            Password = "",
                            PhoneNumber = "0902345678",
                            Username = ""
                        },
                        new
                        {
                            StudentId = 3,
                            Address = "789 Đồng Khởi, Q5, TP.HCM",
                            Avatar = "",
                            DateOfBirth = new DateTime(2000, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "c.le@email.com",
                            EnrollmentDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lê Văn C",
                            IsActive = true,
                            Level = "Pre-Intermediate",
                            Password = "",
                            PhoneNumber = "0903456789",
                            Username = ""
                        });
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualifications")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            Avatar = "",
                            Email = "an.nguyen@englishcenter.com",
                            FullName = "Nguyễn Văn An",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 200000m,
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "0901234567",
                            Qualifications = "TESOL Certificate, MA in English Education",
                            Specialization = "General English, IELTS",
                            Username = ""
                        },
                        new
                        {
                            TeacherId = 2,
                            Avatar = "",
                            Email = "binh.tran@englishcenter.com",
                            FullName = "Trần Thị Bình",
                            HireDate = new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 180000m,
                            IsActive = true,
                            Password = "",
                            PhoneNumber = "0902345678",
                            Qualifications = "CELTA Certificate, BA in English Literature",
                            Specialization = "Business English, Communication",
                            Username = ""
                        });
                });

            modelBuilder.Entity("EnglishCenter.API.Models.TestScore", b =>
                {
                    b.Property<int>("TestScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestScoreId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ListeningScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ReadingScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SpeakingScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("WritingScore")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("TestScoreId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("TestScores");

                    b.HasData(
                        new
                        {
                            TestScoreId = 1,
                            ClassId = 1,
                            Comments = "Good performance in listening and writing. Need more practice in speaking.",
                            ListeningScore = 8.5m,
                            ReadingScore = 7.8m,
                            SpeakingScore = 7.5m,
                            StudentId = 1,
                            TestDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TestName = "Midterm Exam - Unit 1",
                            TotalScore = 8.0m,
                            WritingScore = 8.2m
                        },
                        new
                        {
                            TestScoreId = 2,
                            ClassId = 1,
                            Comments = "Excellent improvement in all skills. Keep up the good work!",
                            ListeningScore = 9.0m,
                            ReadingScore = 8.5m,
                            SpeakingScore = 8.2m,
                            StudentId = 1,
                            TestDate = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TestName = "Final Exam - Unit 1",
                            TotalScore = 8.6m,
                            WritingScore = 8.8m
                        },
                        new
                        {
                            TestScoreId = 3,
                            ClassId = 1,
                            Comments = "Average performance. Should focus more on listening comprehension.",
                            ListeningScore = 6.5m,
                            ReadingScore = 7.0m,
                            SpeakingScore = 7.2m,
                            StudentId = 2,
                            TestDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TestName = "Midterm Exam - Unit 1",
                            TotalScore = 6.9m,
                            WritingScore = 6.8m
                        },
                        new
                        {
                            TestScoreId = 4,
                            ClassId = 1,
                            Comments = "Good understanding of grammar. Vocabulary needs improvement.",
                            ListeningScore = 7.2m,
                            ReadingScore = 8.0m,
                            SpeakingScore = 7.8m,
                            StudentId = 2,
                            TestDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TestName = "Quiz - Grammar & Vocabulary",
                            TotalScore = 7.6m,
                            WritingScore = 7.5m
                        },
                        new
                        {
                            TestScoreId = 5,
                            ClassId = 1,
                            Comments = "Outstanding speaking skills! Very fluent and confident.",
                            ListeningScore = 8.8m,
                            ReadingScore = 8.2m,
                            SpeakingScore = 9.2m,
                            StudentId = 1,
                            TestDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TestName = "Quiz - Conversation Skills",
                            TotalScore = 8.7m,
                            WritingScore = 8.5m
                        },
                        new
                        {
                            TestScoreId = 6,
                            ClassId = 1,
                            Comments = "Below average performance. Requires additional support and practice.",
                            ListeningScore = 5.5m,
                            ReadingScore = 6.0m,
                            SpeakingScore = 6.2m,
                            StudentId = 3,
                            TestDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TestName = "Midterm Exam - Unit 1",
                            TotalScore = 5.9m,
                            WritingScore = 5.8m
                        },
                        new
                        {
                            TestScoreId = 7,
                            ClassId = 1,
                            Comments = "Writing has improved. Still needs work on basic grammar.",
                            ListeningScore = 6.0m,
                            ReadingScore = 6.5m,
                            SpeakingScore = 6.0m,
                            StudentId = 3,
                            TestDate = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TestName = "Assignment - Writing Practice",
                            TotalScore = 6.3m,
                            WritingScore = 6.8m
                        },
                        new
                        {
                            TestScoreId = 8,
                            ClassId = 1,
                            Comments = "Consistent high performance. Ready for advanced level.",
                            ListeningScore = 9.2m,
                            ReadingScore = 8.8m,
                            SpeakingScore = 8.5m,
                            StudentId = 1,
                            TestDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TestName = "Final Exam - Unit 2",
                            TotalScore = 8.9m,
                            WritingScore = 9.0m
                        });
                });

            modelBuilder.Entity("EnglishCenter.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.UserOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("UserOtps");
                });

            modelBuilder.Entity("CurriculumTeacher", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("ParticipantTeachersTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenter.API.Models.Curriculum", null)
                        .WithMany()
                        .HasForeignKey("ParticipatedCurriculumsCurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Attendance", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.Lesson", "Lesson")
                        .WithMany("Attendances")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenter.API.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Class", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishCenter.API.Models.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Curriculum", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.CurriculumDay", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.Curriculum", "Curriculum")
                        .WithMany("CurriculumDays")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.CurriculumSession", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.CurriculumDay", "CurriculumDay")
                        .WithMany("CurriculumSessions")
                        .HasForeignKey("CurriculumDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenter.API.Models.Room", "AssignedRoom")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("EnglishCenter.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("AssignedRoom");

                    b.Navigation("CurriculumDay");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Enrollment", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishCenter.API.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Lesson", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.CurriculumSession", "CurriculumSession")
                        .WithMany("Lessons")
                        .HasForeignKey("CurriculumSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumSession");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Payment", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.RefreshToken", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Schedule", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishCenter.API.Models.Teacher", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.TestScore", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenter.API.Models.Student", "Student")
                        .WithMany("TestScores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.User", b =>
                {
                    b.HasOne("EnglishCenter.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Class", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Course", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Curriculum", b =>
                {
                    b.Navigation("CurriculumDays");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.CurriculumDay", b =>
                {
                    b.Navigation("CurriculumSessions");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.CurriculumSession", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Lesson", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Enrollments");

                    b.Navigation("Payments");

                    b.Navigation("TestScores");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.Teacher", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("EnglishCenter.API.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
